AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack that includes a nested stack

Resources:
  MyNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ## Completar
      Parameters:
        Parameter1: !Sub "my-sample-bucket-${AWS::Region}-${AWS::AccountId}"
        Parameter2: subnet-092cfaa958797419d
        Parameter3: ami-074be47313f84fa38